name: Security & License Compliance

on:
  schedule:
    - cron: '0 3 * * 6' # every Saturday at 3am UTC

jobs:
  security-licenses:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest

      - name: Lint (security, vulnerabilities)
        run: golangci-lint run --timeout 5m

      - name: License compliance (Permissive OSI licenses)
        run: |
          go install github.com/google/go-licenses@latest
          go-licenses check ./... --allowed_licenses=Apache-2.0,MIT,BSD-2-Clause,BSD-3-Clause,ISC

      - name: Check for findings and create issue if needed
        run: |
          if grep -q 'forbidden license' <(go-licenses check ./... --allowed_licenses=Apache-2.0,MIT,BSD-2-Clause,BSD-3-Clause,ISC); then
            gh issue create --title "License Compliance Issue" --body "Forbidden license detected in dependencies." --assignee ${{ github.repository_owner }}
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.1.10
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
