name: Security Compliance

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 6' # every Saturday at 3am UTC

jobs:
  security-licenses:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          # Use Go 1.22 for go-licenses compatibility (see https://github.com/google/go-licenses/issues/128)
          go-version: '1.22'

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest

      - name: Lint (security, vulnerabilities)
        id: lint
        run: |
          golangci-lint run --out-format=short > lint-results.txt
          echo $? > lint-exit-code.txt
          cat lint-results.txt

      - name: Create GitHub issue for linter findings
        if: always()
        run: |
          exit_code=$(cat lint-exit-code.txt)
          if [ "$exit_code" -ne 0 ] && [ -s lint-results.txt ]; then
            gh issue create \
              --title "Security Lint Findings" \
              --body "$(echo 'The following security or vulnerability issues were found by golangci-lint:'; echo; cat lint-results.txt)" \
              --assignee "${{ github.repository_owner }}"
          else
            echo "No linter findings to report."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.1.10
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
